# Generated by Django 4.2.2 on 2023-06-07 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='books',
            options={'verbose_name': 'books', 'verbose_name_plural': 'books'},
        ),
    ]
