# Generated by Django 4.2.2 on 2023-06-07 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0002_category_alter_books_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='book_app.category'),
            preserve_default=False,
        ),
    ]
